services:
  nginx:
    image: nginx:latest
    container_name: nginx
    command: /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - web_net

networks:
  web_net:
    external: true
